# Generated by Django 5.2.1 on 2025-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_scientifique', models.CharField(max_length=200)),
                ('nom_commun', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('famille', models.CharField(blank=True, max_length=100)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('exposition', models.CharField(blank=True, max_length=100)),
                ('arrosage', models.CharField(blank=True, max_length=200)),
                ('humidite', models.CharField(blank=True, max_length=100)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('toxicite', models.BooleanField(default=False)),
                ('floraison', models.CharField(blank=True, max_length=100)),
                ('entretien', models.TextField(blank=True)),
                ('maladies', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
